[scrolling]
history = 10000
multiplier = 3

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[cursor]
blink_interval = 750
[cursor.style]
shape = "Block"
blinking = "Always"

[env]
TERM = "xterm-256color"

# [font]
# normal= {family="Hack Nerd Font", style="Normal"}
# bold= {family="Hack Nerd Font", style="Bold"}
# italic= {family="Hack Nerd Font", style="Italic"}
# bold_italic= {family="Hack Nerd Font", style="Bold Italic"}
# medium_italic= {family="Hack Nerd Font", style="Medium Italic"}
# bold="Hack Nerd Font"
# italic="Hack Nerd Font"
# bold_italic="Hack Nerd Font"
# medium_italic="Hack Nerd Font"
draw_bold_text_with_bright_colors = "true"
size = "12"

# [font.bold]
# family = "Hack Nerd Font"
# style = "Bold"
#
# [font.bolditalic]
# family = "Hack Nerd Font"
# style = "BoldItalic"
#
# [font.italic]
# family = "Hack Nerd Font"
# style = "MediumItalic"
#
# [font.normal]
# family = "Hack Nerd Font"
# style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

# [schemes.tokyo-night.bright]
# black = "0x444b6a"
# blue = "0x7da6ff"
# cyan = "0x0db9d7"
# green = "0xb9f27c"
# magenta = "0xbb9af7"
# red = "0xff7a93"
# white = "0xacb0d0"
# yellow = "0xff9e64"
#
# [schemes.tokyo-night.normal]
# black = "0x32344a"
# blue = "0x7aa2f7"
# cyan = "0x449dab"
# green = "0x9ece6a"
# magenta = "0xad8ee6"
# red = "0xf7768e"
# white = "0x787c99"
# yellow = "0xe0af68"
#
# [schemes.tokyo-night.primary]
# background = "0x1a1b26"
# foreground = "0xa9b1d6"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
